# Generated by Django 4.1.5 on 2023-02-09 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprendimiento',
            name='contacto',
        ),
    ]
