# Generated by Django 4.1.5 on 2023-02-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="codigo",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="producto",
            name="codigo",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
