# Generated by Django 4.1.5 on 2023-02-15 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("codigo", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=30)),
                ("telefono", models.CharField(max_length=10)),
                ("correo", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Emprendimiento",
            fields=[
                ("codigo", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=30)),
                ("decripcion", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=15)),
                ("contacto", models.CharField(max_length=10)),
                ("horario", models.CharField(max_length=30)),
                (
                    "cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("codigo", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=20)),
                ("decripcion", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=15)),
                (
                    "emprendimiento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social.emprendimiento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "codigo",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("cuerpo", models.CharField(max_length=999)),
                (
                    "emprendimiento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social.emprendimiento",
                    ),
                ),
            ],
        ),
    ]
