# Generated by Django 4.1.5 on 2023-02-15 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_alter_comentario_codigo_alter_producto_codigo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emprendimiento", old_name="decripcion", new_name="descripcion",
        ),
    ]
