# Generated by Django 4.1.5 on 2023-01-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "codigo",
                    models.IntegerField(
                        max_length=6, primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("decripcion", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=15)),
            ],
        ),
    ]
