# Generated by Django 4.1.5 on 2023-01-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Social", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("telefono", models.CharField(max_length=10)),
                ("correo", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Emprendimiento",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("decripcion", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=15)),
                ("likes", models.PositiveBigIntegerField()),
            ],
        ),
    ]
