# Generated by Django 4.1.5 on 2023-01-16 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Social", "0003_comentario_cliente_emprendimientos_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cliente", name="emprendimientos",),
        migrations.RemoveField(model_name="emprendimiento", name="comentarios",),
        migrations.RemoveField(model_name="emprendimiento", name="likes",),
        migrations.AddField(
            model_name="comentario",
            name="emprendimiento",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Social.emprendimiento",
            ),
        ),
        migrations.AddField(
            model_name="emprendimiento",
            name="cliente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Social.cliente",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="emprendimiento",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Social.emprendimiento",
            ),
        ),
    ]
